version: '3.8'

services:
    app:
        container_name: dnp3_outstation_rust
        env_file:
            - .env
        environment:
            - RUST_LOG=info
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        networks:
            - scada-network
        ports:
            - "777:777"
        # restart: always

networks:
    scada-network:
        external: true