apiVersion: apps/v1
kind: Deployment
metadata:
    name: dnp3-outstation-deployment
    namespace: simulator-dnp3
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dnp3-outstation
    template:
        metadata:
            labels:
                app: dnp3-outstation
        spec:
            imagePullSecrets:
                -   name: harbor-secret
            containers:
                -   name: dnp3-outstation
                    image: 1.2.3.4/scada/dnp3-outstation:latest
                    ports:
                        -   containerPort: 7777
                    envFrom:
                        -   configMapRef:
                                name: dnp3-outstation-config
---
apiVersion: v1
kind: Service
metadata:
    name: dnp3-outstation-service
    namespace: simulator-dnp3
spec:
    selector:
        app: dnp3-outstation
    type: NodePort
    ports:
        -   name: dnp3-outstation-port-7777
            protocol: TCP
            port: 7777
            targetPort: 7777
            nodePort: 31777
